name: .NET Desktop Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: HomebridgeSpeakerApp.sln
      Project_Path: HomebridgeSpeakerApp/HomebridgeSpeakerApp.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build app
        run: dotnet publish $env:Project_Path --configuration Release --output ./publish

      - name: Upload published app
        uses: actions/upload-artifact@v4
        with:
          name: HomebridgeSpeakerApp-Release
          path: ./publish
