name: .NET Desktop Single-File Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Project_Path: HomebridgeSpeakerApp/HomebridgeSpeakerApp.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish single EXE (self-contained)
        run: |
          dotnet publish $env:Project_Path `
            --configuration Release `
            --runtime win-x64 `
            --self-contained true `
            -p:PublishSingleFile=true `
            -p:IncludeAllContentForSelfExtract=true `
            -p:PublishTrimmed=false `
            --output ./publish

      - name: Upload single EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: HomebridgeSpeakerApp-SingleExe
          path: ./publish/*.exe
