name: Build and Deploy ClickOnce

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish ClickOnce
        run: |
          dotnet publish HomebridgeSpeakerApp/HomebridgeSpeakerApp.csproj `
            --configuration Release `
            /p:PublishDir=./publish/ `
            /p:GenerateManifests=true `
            /p:IsWebBootstrapper=true `
            /p:PublishSingleFile=false `
            /p:InstallUrl="https://raw.githubusercontent.com/${{ github.repository }}/clickonce/" `
            /p:UpdateEnabled=true `
            /p:UpdateUrl="https://raw.githubusercontent.com/${{ github.repository }}/clickonce/"

      - name: Upload ClickOnce files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: clickonce-publish
          path: publish

      - name: Deploy to ClickOnce branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan clickonce
          git rm -rf .
          cp -R publish/* .
          git add .
          git commit -m "Deploy ClickOnce files"
          git push --force origin clickonce
